;; elfeed.el

(unless (package-installed-p 'elfeed)
  (package-install 'elfeed))

(require 'elfeed)

(global-set-key (kbd "C-x w") 'elfeed)

(setq elfeed-feeds
	'(("http://www.456bereastreet.com/feed.xml" css)
	  ("http://feeds.feedburner.com/adequatelygood" javascript)
	  ("http://shiflett.org/rss" security web)
	  ("http://blog.markrendle.net/feed/" .net)
	  ("http://coreygoldberg.blogspot.com/feeds/posts/default" python linux ubuntu)
	  ("http://feeds.feedburner.com/deanedwards/weblog" javascript)
	  ("http://donmelton.com/rss.xml" apple)
	  ("http://www.dustincurtis.com/rss.xml" design)
	  ("http://emacsrocks.com/atom.xml" emacs)
	  ("http://feeds.feedburner.com/catonmat" programming)
	  ("http://googletesting.blogspot.com/feeds/posts/default" google testing)
	  ("http://guitarnoize.com/feed/" guitars)
	  ("http://www.stevesouders.com/blog/feed/" web performance)
	  ("http://www.igvita.com/feed/" web performance)
	  ("http://blog.jonudell.net/feed/" web internet)
	  ("http://leahculver.com/feed/" python web)
	  ("http://martinfowler.com/bliki/bliki.atom" programming)
	  ("http://feeds.feedburner.com/miraculous" web javascript)
	  ("http://morethanseven.net/articles.atom" web programming)
	  ("http://feeds.nczonline.net/blog/" javascript web)
	  ("http://paulirish.com/feed/" web chrome javascript)
	  ("http://feeds.feedburner.com/PersistentInfo" programming web)
	  ("http://philsherry.com/feed/" web)
	  ("http://pragprog.com/feed/global" programming books)
	  ("http://samsaffron.com/posts.rss" web programming ruby)
	  ("http://feeds.feedburner.com/ScottHanselman" web programming .net)
	  ("http://weblogs.asp.net/scottgu/rss.aspx" web programming .net)
	  ("http://blog.getdropbox.com/?feed=rss2" dropbox)
	  ("http://engineering.twitter.com/feeds/posts/default?alt=rss" twitter programming)
	  ("http://whattheemacsd.com/atom.xml" emacs)
	  ("http://xkcd.com/atom.xml" comic)
	  ("http://feeds.haacked.com/haacked/" programming github .net)
	  ("http://feeds.feedburner.com/holman" programming ruby github)
	  ("http://www.howardism.org/index.xml" emacs programming)
	  ("http://nullprogram.com/feed/" emacs programming)))

